### ISSUE TITLE
On macOS the zoom control buttons don't work with a tap gesture

### ISSUE THREAD

**Issue by sena-mike** [sena-mike/SwiftUIAdvancedMap#12]

**Comment by HanSolo** [comment]
See the same and it looks like the tapOrClickHandler catches the event so that it can't reach the zoom control buttons, maybe a z-index problem? Just guessing...

**Comment by sena-mike** [comment]
> maybe a z-index problem

Yea the zoom control buttons are subviews of `MKMapView`, adding the gesture recognizer to `MKMapView` prevents the gesture recognizer of subviews from working. Probably need to implement something like: 

https://stackoverflow.com/questions/19592622/uitapgesturerecognizer-on-uiview-and-its-subview-respond-together-when-subview-i

**Comment by sena-mike** [comment]
fixed in https://github.com/sena-mike/SwiftUIAdvancedMap/pull/15
