### ISSUE TITLE
Make configuration accessible

### ISSUE THREAD

**Issue by HanSolo** [sena-mike/SwiftUIAdvancedMap#18]
I might be wrong but as far as I can see the configuration of the map is final and cannot be changed after initialized. It would be nice to have the ability to change the configuration at runtime e.g. from .standard to .hybrid. Or is there already the ability to change this?

**Comment by sena-mike** [comment]
Ah yea that's right and unfortunate. Should be able add that

**Comment by sena-mike** [comment]
Actually this should Just Work™️, the configuration is updated each time the view's body is rendered. https://github.com/sena-mike/SwiftUIAdvancedMap/blob/main/Sources/AdvancedMap/AdvancedMap%2BViewRepresentable.swift#L58-L74


https://user-images.githubusercontent.com/1428315/213885818-67f1a47a-3d22-488b-a84e-907438e8b370.mov

Although, there does seem to be an issue where changing the configuration causes the zoom level to change. Will create a separate issue to track that.

**Comment by HanSolo** [comment]
Nice, will test it. Thanks a lot 👍🏻

**Comment by sena-mike** [comment]
Added a sample:
https://github.com/sena-mike/SwiftUIAdvancedMap/blob/eab9ef4b566c9f11af117e92f21ba45d6bafdc37/Example/Example/ConfigurationView.swift
